### PR TITLE
New API Events New API Events and little fix in open() method

### PR DESCRIPTION
**Pull request by creativejuiz**
Hi there,

My contribution by adding some events I use everytime.

Thank you for taking a look at it.

Nice day,
Geoffrey

### CODE REVIEW

**Comment by andreknieriem** [comment]
Hey, thanks for the big commit! I will take a look at it and merge it.

**Comment by creativejuiz** [comment]
You are welcome :)

Lot of commits but little editions here and there. 

Thank you for the great tool by the way.

**Comment by andreknieriem** [comment]
Merged in Version 1.8.0! Thanks!

**Comment by creativejuiz** [comment]
Sorry for my silence.
Thank you! :)

**Pull request closed without merging**
