### PR TITLE
fixes #332 Adds missing AVIF support

### LINKED ISSUE #332: Missing AVIF extension support
Can we add AVIF image extension support?

Thank you

### PR DESCRIPTION
**Pull request by quicoto**
This PR adds support for AVIF image format

fixes #332

### CODE REVIEW

**Comment by quicoto** [comment]
@andreknieriem May I ask for a review?

Thank you very much

**Comment by Mtillmann** [comment]
looks good to me - merging

**Comment by quicoto** [comment]
Thank you @Mtillmann Will you also do a new release with this so it's available on NPM?

**Comment by Mtillmann** [comment]
@quicoto good point. @andreknieriem

**Comment by quicoto** [comment]
Any update on this @Mtillmann @andreknieriem ?

Thank you

**Pull request merged**
